# -*- coding: UTF-8 -*-
SECRET_KEY = "I_LOVE_PYTHON_NMSL"

ELASTIC_HOST = "http://localhost:9200"
ELASTIC_INDEX = "sogou0016"
ELASTIC_INDEX_WITH_PART = "sogou0016.out"
ELASTIC_TYPE = "line"
ELASTIC_URL = "/".join((ELASTIC_HOST, ELASTIC_INDEX, ELASTIC_TYPE))
ELASTIC_URL_WITH_PART = "/".join((ELASTIC_HOST, ELASTIC_INDEX_WITH_PART, ELASTIC_TYPE))
